name: "Changelog Enforcer"
on:
 #pull_request:
 #  types: [opened, synchronize, reopened]

  workflow_dispatch:
    
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: modpack/CHANGELOG.md
